/*
nycct_prelude.mac

NYCCT physics lab.
*/

print("
nycct_prelude.mac
 
A list of formula:
  percent_err(ve, vst) 
  percent_diff(v1,v2)

");

/* least square fit */
load("least_square_fit.mac"); 

percent_err(ve, vst) := block(
  [num, den],
  num : abs( ve - vst ),
  den : vst,
  return( num/den * 100)
);

percent_diff(v1,v2) := block(
  [num, den],
  num : abs(v1 - v2),
  den : (v1+v2)/2,
  return( num/den * 100)
);

